### ISSUE TITLE
company-go: unwanted completion menu pops up right after left curly brace

### ISSUE THREAD

**Issue by ijt** [mdempsky/gocode#105]
### What version of Go are you using (`go version`)?

go version go1.11.2 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/issactrotts/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/issactrotts"
GOPROXY=""
GORACE=""
GOROOT="/Users/issactrotts/homebrew/Cellar/go/1.11.2/libexec"
GOTMPDIR=""
GOTOOLDIR="/Users/issactrotts/homebrew/Cellar/go/1.11.2/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/x7/5zsztt1s5c1gc_7prrq9zn5h001n0v/T/go-build769989674=/tmp/go-build -gno-record-gcc-switches -fno-common"

### What is the debug output of `gocode`?

I changed the code to this:

```
(defun company-go--invoke-autocomplete ()
  (let ((temp-buffer (generate-new-buffer "*gocode*")))
    (prog2
        (call-process-region (point-min)
                             (point-max)
                             company-go-gocode-command
                             nil
                             temp-buffer
                             nil
                             "-f=csv"
			     "-s" "-debug"
                             "autocomplete"
                             (or (buffer-file-name) "")
                             (concat "c" (int-to-string (- (point) 1))))
        (with-current-buffer temp-buffer (buffer-string))
      (kill-buffer temp-buffer))))
```

The next time completion occurred, emacs hung.

### What (client-side) flags are you passing into `gocode`?

Here's the call:
```
(defun company-go--invoke-autocomplete ()
  (let ((temp-buffer (generate-new-buffer "*gocode*")))
    (prog2
        (call-process-region (point-min)
                             (point-max)
                             company-go-gocode-command
                             nil
                             temp-buffer
                             nil
                             "-f=csv"
                             "autocomplete"
                             (or (buffer-file-name) "")
                             (concat "c" (int-to-string (- (point) 1))))
        (with-current-buffer temp-buffer (buffer-string))
      (kill-buffer temp-buffer))))
```

### What editor are using?

Emacs.

Here's how to reproduce the problem. Put this code in a Go file:

```
package foo

type T struct {
}

func New() *T {
	return &T{}
}

func (t *T) String()
```
At the end of the last line, type a left curly brace "{" and then hit return or enter. 

Expected: The cursor should just go to the next line.
Actual: A menu pops up and then hitting enter selects something from the menu and inserts it right after the left curly brace.

Here is the configuration in my `.emacs`:
```
(require 'company)
(require 'company-go)
(setq company-minimum-prefix-length 0)  ; Otherwise you have to type some letters after the dot to get completion.
;; Only enable the company-go backend when editing Go files.
(add-hook 'go-mode-hook (lambda ()
                          (set (make-local-variable 'company-backends) '(company-go))
                          (company-mode)))
(setq company-tooltip-limit 20)                      ; bigger popup window
(setq company-idle-delay .3)                         ; decrease delay before autocompletion popup shows
(setq company-echo-delay 0)                          ; remove annoying blinking
(setq company-begin-commands '(self-insert-command)) ; start autocompletion only after typing
```

**Comment by stamblerre** [comment]
Thanks for the report! Because company-go is just carried over from https://github.com/nsf/gocode, and gocode is just being maintained until gopls is ready (and I am not very familiar with elisp), I will not be able to dedicate time to fixing this myself. If you or anyone else wants to submit a PR, I will be happy to merge it.

**Comment by ijt** [comment]
Sure! In that case maybe it's best to wait until gopls is ready.

**Comment by stamblerre** [comment]
Closing this issue as a result. All PRs are welcome.
