### ISSUE TITLE
gocode: serverless mode

### ISSUE THREAD

**Issue by kostya-sh** [mdempsky/gocode#11]
Currently gocode is a thin client that talks to a server process using net/rpc.

However as far as I can tell the server (unlike the original nsf/gocode version) doesn't cache anything.

A client that uses suggest package to find the list of candidates is going to be simpler and probably even a few ms faster.

I suggest to implement a serverless mode for the client first (e.g. by passing -addr=none on the command line).

If it proves to be fast and usable enough maybe the server can be removed alltogether.

Thoughts?

**Comment by mdempsky** [comment]
I've thought about that some too. The main reason I've kept the server design was in case we end up needing caching.

But a flag to try using suggest directly within the client seems like a reasonable first step/experiment.

**Comment by mdempsky** [comment]
I just experimented with this a little bit, and counter-intuitively, using an RPC to the server is still marginally faster.  Using package suggest directly within client.go seems to always take about 30ms--40ms, whereas using an RPC to the server generally takes around 10ms--15ms.

**Comment by mdempsky** [comment]
Another possibility to simplify things would be to have editors speak some RPC protocol directly to the gocode "server". E.g., sending JSON over local HTTP or just streaming multiple requests via stdin/stdout to a single gocode process. That would theoretically eliminate both the overhead from the extra Go client process and the extra step of proxying RPCs.

Downside would be that involves modifying the editor integration scripts, and the new scripts would no longer be backwards compatible with nsf/gocode, unless the changes are made there too.

**Comment by mdempsky** [comment]
It occurred to me that I was accidentally caching loaded package export data due to gbimporter. I suspect that accounts for why having the long-lived server process was faster. I'll have to measure again tomorrow.

**Comment by kostya-sh** [comment]
I can see this too. Even with the server the first call to Suggest is
slower than subsequent calls (40ms vs 15ms). This is because
go/types/importer.Default() is effectively a cache of parsed packages.

The change to make the client optionally work without the server is fairly
straightforward, though probably less useful than I originally thought.

If you still think it is a good idea I can send a pull request.

**Comment by LK4D4** [comment]
@mdempsky @kostya-sh Guys, do you understand where `go/importer` stores its cache?
I did not look at theGpackage before, but now it seems that `Default()` returns new importer each time. Also, I don't see speedup between first and subsequent calls now.
EDIT: I've tried to cache importers in a map and it became blazingly fast, not sure if it's a good idea regarding editing code.

**Comment by kostya-sh** [comment]
@LK4D4 , gocode used to cache imported packages. it was changed in https://github.com/mdempsky/gocode/commit/7f107ea59dcfced23eecea81a02417a69c2cdd50, the commit message explains why.

**Comment by LK4D4** [comment]
@kostya-sh thanks for explanation!

**Comment by LK4D4** [comment]
@mdempsky @kostya-sh then I suppose client-only feature would be cool. Also, it should be faster if we disable garbage collector in client-only mode, because `go/types` generates tons of garbage and GC is top cpu consumer in gocode.

**Comment by LK4D4** [comment]
I did not notice significant speedup from client-side suggest only. But GOGC=off shaves off 30% of time for me.

**Comment by kostya-sh** [comment]
I have necessary changes for the client-side mode. I will submit a PR soon.

A cache with inotify-based invalidation on the server side will likely be faster though.
