### ISSUE TITLE
gocode: not restarting

### ISSUE THREAD

**Issue by yozamacs** [mdempsky/gocode#116]
Please answer these questions before submitting your issue. Thanks!
Also, remember that to restart gocode, you have to run `gocode close`.

### What version of Go are you using (`go version`)?
go version go1.12.6 darwin/amd64

### What operating system and processor architecture are you using (`go env`)?
darwin, amd64

### What is the debug output of `gocode`?
 
Run `gocode close` and then run `gocode -s -debug` to restart gocode in debug mode. 
Try to complete once again from your editor, and paste the output printed by gocode here.

running `gocode close` results in 
```
2019/07/10 15:26:54 dial unix /var/folders/_q/fbbhjg5s5j3gmcj3mv5qr6200000gn/T/gocode-daemon.maryum: connect: no such file or directory
```
running `gocode -s -debug` just hangs

### What (client-side) flags are you passing into `gocode`?
none....should I be?
Please note here if you are using `-source`, `-builtin`, `-ignore-case`, `-unimported-packages`, or `-fallback-to-source`.

### What editor are using?
atom, but I'm seeing the same errors on the command line

**Comment by stamblerre** [comment]
If you get an error from `gocode close`, then you likely did not have a `gocode` server running.
`gocode -s -debug` starts `gocode` in server mode, meaning that you will not see any output until you send it a request. This can be done through your editor or by manually constructing a request on the command-line.

**Comment by stamblerre** [comment]
Closing, as the tool is no longer supported: https://github.com/mdempsky/gocode#important-this-repository-is-currently-in-maintenance-mode.
