### ISSUE TITLE
emacs MELPA packages

### ISSUE THREAD

**Issue by kostya-sh** [mdempsky/gocode#12]
Currently there are 2 gocode MELPA packages:
- http://melpa.org/#/company-go
- http://melpa.org/#/go-autocomplete

Both of them use nsf/gocode as a source. So any improvements made to mdempsky/gocode (such as https://github.com/mdempsky/gocode/commit/4dd2f3d3a5b1683ec3a79beea21fdeb606ae62f3) do not end up on MELPA.

It would be good to have a single repo for these emacs packages and make sure that they work with both versions of gocode.

cc @nsf

**Comment by nsf** [comment]
I don't mind, I don't use emacs anyway. These packages just happen to be in my repo, but my interest in them is on a "gocode text editor integration example" level.

**Comment by robbyoconnor** [comment]
Bumping this -- I'd be in favor of switching this.

**Comment by stamblerre** [comment]
At this point, https://github.com/nsf/gocode is not longer supported, so we can make this switch. 

Edit: Opened https://github.com/melpa/melpa/pull/5753.

**Comment by stamblerre** [comment]
https://github.com/melpa/melpa/pull/5753 was merged. Closing.
