### ISSUE TITLE
Code completion always shows "PANIC"

### ISSUE THREAD

**Issue by leolin49** [mdempsky/gocode#120]
Please answer these questions before submitting your issue. Thanks!
Also, remember that to restart gocode, you have to run `gocode close`.

### What version of Go are you using (`go version`)?
1.16.6

### What operating system and processor architecture are you using (`go env`)?
linux/amd64

### What is the debug output of `gocode`?

Run `gocode close` and then run `gocode -s -debug` to restart gocode in debug mode. 
Try to complete once again from your editor, and paste the output printed by gocode here.

![image](https://user-images.githubusercontent.com/58925286/131513501-848dbf87-5ea1-4e4b-92f1-a69fe1274f03.png)

### What (client-side) flags are you passing into `gocode`?

Please note here if you are using `-source`, `-builtin`, `-ignore-case`, `-unimported-packages`, or `-fallback-to-source`.

### What editor are using?
vim8.0   Vundle

**Comment by stamblerre** [comment]
This tool is no longer supported: https://github.com/mdempsky/gocode#important-this-repository-is-currently-in-maintenance-mode. Please switch to one of the following Vim plugins for gopls: https://github.com/golang/tools/blob/master/gopls/doc/vim.md.
