### ISSUE TITLE
high cpu consumption/slowness on emacs using Go tip

### ISSUE THREAD

**Issue by rjammala** [mdempsky/gocode#17]
Hi

When I tried to use gocode (compiled with tip version of Go on Linux/amd64), I noticed that it is consuming a lot of cpu and it is freezing/slowing down emacs. 

$ go version
go version devel +fb3cf5c Mon Jul 11 15:11:44 2016 +0000 linux/amd64

$emacs --version
GNU Emacs 25.0.94.1
Copyright (C) 2016 Free Software Foundation, Inc.

$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/rjammalamadaka/gocode"
GORACE=""
GOROOT="/home/rjammalamadaka/go"
GOTOOLDIR="/home/rjammalamadaka/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build120557061=/tmp/go-build"
CXX="g++"
CGO_ENABLED="1"

Not sure if anyone else noticed this. Here is what I tried to type: https://play.golang.org/p/2j5PPxh9UN
I use goimports to manage the imports.

Here is the debug info from gocode, please let me know if you need anything else.

$ ~/gocode/bin/gocode -s -debug
2016/07/11 12:28:49 Got autocompletion request for '/home/rjammalamadaka/tchannel.go'
2016/07/11 12:28:49 Cursor at: 45
2016/07/11 12:28:49 -------------------------------------------------------
package main

func main() {

```
http.HandleFunc#("dnsfile", 
```

}
2016/07/11 12:28:49 -------------------------------------------------------
2016/07/11 12:28:49 Error parsing input file (outer block):
2016/07/11 12:28:49  /home/rjammalamadaka/tchannel.go:5:28: expected ')', found ','
2016/07/11 12:28:50 Elapsed duration: 601.813606ms
2016/07/11 12:28:50 Offset: 0
2016/07/11 12:28:50 Number of candidates found: 0
2016/07/11 12:28:50 Candidates are:
2016/07/11 12:28:50 =======================================================
2016/07/11 12:28:57 Got autocompletion request for '/home/rjammalamadaka/tchannel.go'
2016/07/11 12:28:57 Cursor at: 49
2016/07/11 12:28:57 -------------------------------------------------------
package main

func main() {

```
http.HandleFunc("/f#
```

}

**Comment by rjammala** [comment]
I am not sure if it matters but I created this program as a standalone program in my home directory in which there are 111 other Go programs. Is that probably the cause?

**Comment by rjammala** [comment]
FWIW, I do not see this issue with nsf/gocode

cc: @mdempsky

**Comment by mdempsky** [comment]
Do I understand correctly that you have 111 other "package main" files in the same directory?  But presumably that they're not actually part of the file you're working on?

If so, then that's probably to be expected, unfortunately.  The current logic (inherited from nsf/gocode) is to find all of the files in the current directory with the same package name, and assume they're part of the same package.  That means we have to typecheck all 111 files together as a single package.

This is perhaps a case where nsf/gocode's caching pays off.  I'd suggest organizing independent programs into separate directories though, to better interoperate with other tools that expect 1 directory == 1 package.

**Comment by rjammala** [comment]
yes, I have 111 other "package main" files. Thanks for the clarification. Will close this issue.

**Comment by mdempsky** [comment]
No problem.  Thanks for letting me know about this problematic use case.
