### ISSUE TITLE
suggest: disambiguate struct literal contexts from function contexts

### ISSUE THREAD

**Issue by mdempsky** [mdempsky/gocode#27]
nsf/gocode committed nsf/gocode@1a78dd6c36d7f37cbb60073523c2e9ca3f6519fa to handle completions like

    func f() StructType {
       @
    }

Currently, suggest thinks this is a StructType literal context (and so it suggests StructType's fields), but actually it's the start of a function block context (so it *should* suggest in-scope identifiers).

The above commit is incomplete, however. It doesn't handle cases like:

    package p

    func f() int

    type T struct { g int }
    func (T) m() int

    var _ = f() * T{ @ }.m()

This should suggest "var g int", but nsf/gocode suggests "func f()" and "type T struct".

**Comment by stamblerre** [comment]
I can confirm that `gopls` handles these cases. Closing this issue as obsolete.
