### ISSUE TITLE
suggest: implement caching

### ISSUE THREAD

**Issue by mdempsky** [mdempsky/gocode#28]
In generating suggestions for cmd/compile/internal/ssa, the two big time overheads are:

  1) Parsing the sibling source files within the package
  2) Loading imports

If we could cache these results, then we'd be on par with nsf/gocode for suggestion performance.

**Comment by mdempsky** [comment]
In the [cache](https://github.com/mdempsky/gocode/commits/cache) branch, I've prototyped caching for both of these. Suggestions within cmd/compile/internal/gc now take on the order of 30ms to 40ms with a warm cache.

**Comment by OneOfOne** [comment]
I've been using this for a few days now (with both go 1.10 and master), I didn't run into any issues and does seem as fast if not faster than nsf's.

**Comment by OneOfOne** [comment]
Any chance this could be merged to make it easier to pull from editors that use this gocode fork?

**Comment by OneOfOne** [comment]
Using -source without this branch is pretty much unusable on a big'ish repo.

**Comment by abennett** [comment]
Let us know what support we can provide.

**Comment by phenixrizen** [comment]
https://github.com/mdempsky/gocode/pull/51 Implements a cache and solves this issue

**Comment by charlievieth** [comment]
See: https://github.com/mdempsky/gocode/pull/55 and https://github.com/mdempsky/gocode/pull/54 as well.

**Comment by stamblerre** [comment]
Cache branch was merged in #71.
