### ISSUE TITLE
Add SublimeText 3 setup instructions

### ISSUE THREAD

**Issue by alexedwards** [mdempsky/gocode#31]
Would it be possible to add setup instructions for SublimeText3 to the README, similar to the instructions for Emacs and Vim?

It looks like the gocode package contains the appropriate ST3 plugin (https://github.com/mdempsky/gocode/tree/master/subl3) but I haven't been able to get it working. Some basic setup instructions would be a great help.

**Comment by alexedwards** [comment]
I figured out how to make it work. I'll submit a PR adding instructions to the README shortly.

**Comment by mdempsky** [comment]
Sorry, I don't use SublimeText, and that plugin was inherited from nsf/gocode, so I don't know how to use it.

Did you write up instructions on how to use it? I didn't see a PR.

**Comment by jostyee** [comment]
I once modified nsf's codes to make this plugin to work on Mac, and support this repo's serverless mode https://github.com/jostyee/gocode-subl3 , so far so good.

**Comment by alexedwards** [comment]
Thanks for the reminder. PR sent.
