### ISSUE TITLE
Vscode does not prompt "built-in"

### ISSUE THREAD

**Issue by jsls2517** [mdempsky/gocode#34]
Vscode does not prompt "built-in"

**Comment by willxm** [comment]
the same problem

**Comment by mdempsky** [comment]
Can you please elaborate?

Best would be if you can provide a minimal Go test file, where your cursor is within the file when you request completion, what completions you're receiving, and what completions you expected.

Thanks.

**Comment by willxm** [comment]
before, I use github.com/nsf/gocode, the built-in prompt is working
<img width="711" alt="screen shot 2018-06-27 at 11 40 40 pm" src="https://user-images.githubusercontent.com/12049565/41985373-b9c1e91c-7a65-11e8-9b97-0b0a89f1a55c.png">
after, I remove the github.com/nsf/gocode and install github.com/mdempsky/gocode.
Unfortunately,  built-in prompt is not working.
<img width="304" alt="screen shot 2018-06-27 at 11 52 42 pm" src="https://user-images.githubusercontent.com/12049565/41985522-1d67ea2a-7a66-11e8-854d-9c04b9c8a3d9.png">

Thanks.

**Comment by mdempsky** [comment]
I see. In github.com/mdempsky/gocode/suggest/candidate.go there's:

	// TODO(mdempsky): Change this to true.
	const proposeBuiltins = false

If you change that from `false` to `true`, reinstall gocode (i.e., `go install github.com/mdempsky/gocode`), and restart gocode (`gocode exit`), it should suggest those built-ins.

Can you test that out and let me know if it works as you expect? If so, I'll look into enabling it by default.

**Comment by willxm** [comment]
I change that
<img width="533" alt="screen shot 2018-07-04 at 9 17 54 am" src="https://user-images.githubusercontent.com/12049565/42252148-be0ce384-7f6d-11e8-91e6-e8df139bc373.png">
restart
<img width="643" alt="screen shot 2018-07-04 at 9 19 07 am" src="https://user-images.githubusercontent.com/12049565/42252159-cf3cd862-7f6d-11e8-9b65-89b39c8d7762.png">
```
geocode -s -debug
```
but panic...

2018/07/04 09:28:01 -------------------------------------------------------
2018/07/04 09:28:01 Error parsing input file (outer block):
2018/07/04 09:28:01  /Users/willxm/go/src/test/problem/main.go:31:6: expected selector or type assertion, found ';'
panic: runtime error: invalid memory address or nil pointer dereference

goroutine 23 [running]:
runtime/debug.Stack(0xb, 0xc4207b7410, 0x1)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/debug/stack.go:24 +0xa7
runtime/debug.PrintStack()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/debug/stack.go:16 +0x22
main.(*Server).AutoComplete.func1(0xc420172640)
	/Users/willxm/go/src/github.com/mdempsky/gocode/server.go:71 +0x94
panic(0x141e1a0, 0x16fbb40)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:505 +0x229
go/types.(*Package).Path(...)
	/usr/local/Cellar/go/1.10/libexec/src/go/types/package.go:30
github.com/mdempsky/gocode/suggest.(*candidateCollector).asCandidate(0xc4200a45b0, 0x14fe820, 0xc4200932c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/willxm/go/src/github.com/mdempsky/gocode/suggest/candidate.go:126 +0x140
github.com/mdempsky/gocode/suggest.(*candidateCollector).getCandidates(0xc4200a45b0, 0xc4207a9d10, 0xc4200a45b0, 0x151)
	/Users/willxm/go/src/github.com/mdempsky/gocode/suggest/candidate.go:94 +0xeb
github.com/mdempsky/gocode/suggest.(*Config).Suggest(0xc4207b7aa0, 0xc420164c30, 0x29, 0xc4200d06e0, 0x153, 0x153, 0x150, 0x170d080, 0x143df40, 0xc420050a90, ...)
	/Users/willxm/go/src/github.com/mdempsky/gocode/suggest/suggest.go:71 +0x2b6
main.(*Server).AutoComplete(0x172b100, 0xc4200896c0, 0xc420172640, 0x0, 0x0)
	/Users/willxm/go/src/github.com/mdempsky/gocode/server.go:102 +0x1fc
reflect.Value.call(0xc4200744e0, 0xc42000e580, 0x13, 0x149ea5b, 0x4, 0xc420050f18, 0x3, 0x3, 0xc420071b40, 0x13f7700, ...)
	/usr/local/Cellar/go/1.10/libexec/src/reflect/value.go:447 +0x969
reflect.Value.Call(0xc4200744e0, 0xc42000e580, 0x13, 0xc42016ef18, 0x3, 0x3, 0x1469ba0, 0x1480401, 0xc420070200)
	/usr/local/Cellar/go/1.10/libexec/src/reflect/value.go:308 +0xa4
net/rpc.(*service).call(0xc420071a00, 0xc420092690, 0xc420176198, 0xc4201761b0, 0xc4200a6400, 0xc420108de0, 0x13e3560, 0xc4200896c0, 0x16, 0x13e3520, ...)
	/usr/local/Cellar/go/1.10/libexec/src/net/rpc/server.go:384 +0x14e
created by net/rpc.(*Server).ServeCodec
	/usr/local/Cellar/go/1.10/libexec/src/net/rpc/server.go:480 +0x43a
2018/07/04 09:28:02 Got autocompletion request for '/Users/willxm/go/src/test/problem/main.go'
2018/07/04 09:28:02 Cursor at: 338

**Comment by mdempsky** [comment]
Sorry about that. I tested that before recommending it, but apparently had an old checkout.

I believe I've fixed proposeBuiltins at master. Please try again. Thank you.

**Comment by mdempsky** [comment]
Suggestions for builtins are now controlled by a `-builtin` flag in the client. If you can configure VS Code to set that flag, you should get the suggestions you're expecting.

If there's a preferable way to integrate that customization into VS Code, let me know.

**Comment by willxm** [comment]
I restart gocode
```
gocode -s -builtin -debug
```
output

2018/07/04 11:11:19 =======================================================
2018/07/04 11:11:19 Got autocompletion request for '/Users/willxm/go/src/test/problem/main.go'
2018/07/04 11:11:19 Cursor at: 36
2018/07/04 11:11:19 -------------------------------------------------------
package main

func main() {
	var s s#
}
2018/07/04 11:11:19 -------------------------------------------------------
2018/07/04 11:11:19 Elapsed duration: 259.846µs
2018/07/04 11:11:19 Offset: 0
2018/07/04 11:11:19 Number of candidates found: 1
2018/07/04 11:11:19 Candidates are:
2018/07/04 11:11:19   var s invalid type
2018/07/04 11:11:19 =======================================================

<img width="270" alt="screen shot 2018-07-04 at 11 14 25 am" src="https://user-images.githubusercontent.com/12049565/42254871-7ab6d802-7f7b-11e8-8eaf-385fadec484f.png">


also can not prompt "builtin", it's right ?

**Comment by ramya-rao-a** [comment]
Thanks for the fix @mdempsky! I've verified that it works as intended.

@willxm Please follow the below to try the integrated fix in VS Code. I'll release an update early next week.

- Download https://github.com/Microsoft/vscode-go/blob/master/Go-latest.vsix
- Run `code --install-extension Go-latest.vsix` 
- If the above fails with `Error: end of central directory record signature not found`, then clone this repo, switch to branch `source` and use the `Go-latest.vsix` file 
- Reload VS Code
- If you get a prompt to update `gocode`, go ahead and update it

**Comment by ramya-rao-a** [comment]
@mdempsky Any thoughts on #32? Looks like using the `-source` flag is the solution but that makes completions very slow. Any updates on the `cache` branch?
