### ISSUE TITLE
intellisense autocompletion stops working

### ISSUE THREAD

**Issue by iiinsomnia** [mdempsky/gocode#36]
![image](https://user-images.githubusercontent.com/6582246/42077797-9a20b08c-7bac-11e8-886a-0fc86b8c8d5c.png)

![image](https://user-images.githubusercontent.com/6582246/42077817-b4455c38-7bac-11e8-85c8-8d80669c71ed.png)

golang version: 1.10.3

**Comment by Hawken94** [comment]
I met the same question.

**Comment by mdempsky** [comment]
Sorry, but you need to give at least a little more context than that.

Can you provide a minimal reproduction case?

**Comment by iiinsomnia** [comment]
Autocompletion for built-in type and built-in functions stop working, eg: append()、delete() etc.

**Comment by ramya-rao-a** [comment]
@IIInsomnia The issue with built-in types is covered in #34

**Comment by iiinsomnia** [comment]
thanks.
