### ISSUE TITLE
No completions for packages in the import block

### ISSUE THREAD

**Issue by ramya-rao-a** [mdempsky/gocode#38]
When using nsf/gocode, we get completions for packages in the import block. The same isn't available when using mdempsky/gocode.

For example: In the below code, trigger completions from inside the `""` in the import block

```
package main

import (
	""
)

func main() {
	
}
```

nsf/gocode gives:

<img width="672" alt="screen shot 2018-07-15 at 5 31 48 pm" src="https://user-images.githubusercontent.com/16890566/42739951-ef2ddf1e-8854-11e8-8225-191f42a46f9d.png">

mdempsky/gocode gives:
<img width="1024" alt="screen shot 2018-07-15 at 5 30 41 pm" src="https://user-images.githubusercontent.com/16890566/42739953-f9789194-8854-11e8-8cfc-e5f940de25a7.png">

**Comment by scottjbarr** [comment]
That won't compile, so I personally wouldn't expect it to work.

**Comment by hellupline** [comment]
the issue is not the dummy code that cant compile, 
its a missing feature from nsf/gocode which mdempsky/gocode doesn't have

**Comment by mohanson** [comment]
Steps to Reproduce:
1. vi main.go
2. input "net/" can't get import suggestions(in "nsf/gocode", "net/http" will be suggested)

**Comment by segevfiner** [comment]
Related commits from `nsf/gocode`: https://github.com/nsf/gocode/commit/9e6ef41d7b072f389a4675b0f7718dedb232cb96 and https://github.com/nsf/gocode/commit/40385eba48ae61394e5d2935b1e5c7130fa9b46b.

**Comment by stamblerre** [comment]
I'm happy to review PRs for this feature, but I don't think I will have time to implement it myself.

**Comment by JackieLs** [comment]
Look forward to this feature ......

**Comment by segevfiner** [comment]
As I said, I think this exists in nsf/gocode and I pointed to the relevant commits in a previous comment. So instead of implementing, I think this just needs merging/cherry-picking. There might be other such bug fixes/features in nsf/gocode that were contributed to it before this fork became the recommended version.

**Comment by jsfaint** [comment]
@segevfiner I'm looking for this feature too.
But it looks the code structure between these two repo is totally different since long time ago.
The commit can't be used directly.

**Comment by stamblerre** [comment]
This is something we are tracking for `gopls` in https://github.com/golang/go/issues/35877. Since this repository is in maintenance mode, it won't be implemented here.
