### ISSUE TITLE
Panics with Go 1.11beta1/2: unknown export format version -1 ("i\x00\xf9")

### ISSUE THREAD

**Issue by fd0** [mdempsky/gocode#43]
Apparently, in Go 1.11 the binary format for the archives was changed (see also https://github.com/nsf/gocode/issues/521#issuecomment-401094761), any chance you may have time (or know someone) who could adapt the parser for the format? That'd be awesome! Not having any code completion in 1.11 made me realize how important this is...

The error and stacktrace is as follows:
```
$ gocode -s -debug
[...]
2018/07/21 13:42:36 Found "github.com/restic/restic/internal/test" at "/home/fd0/shared/work/go/pkg/linux_amd64/github.com/restic/restic/internal/test.a"
panic: unknown export format version -1 ("i\x00\xf9")
1(runtime.call32): /home/fd0/sdk/go1.11beta2/src/runtime/asm_amd64.s:522
2(runtime.gopanic): /home/fd0/sdk/go1.11beta2/src/runtime/panic.go:513
3(main.(*gc_bin_parser).parse_export): /home/fd0/shared/work/go/src/mod/github.com/nsf/gocode@v0.0.0-20180502111240-9d1e0378d35b/package_bin.go:126
4(main.(*package_file_cache).process_package_data): /home/fd0/shared/work/go/src/mod/github.com/nsf/gocode@v0.0.0-20180502111240-9d1e0378d35b/package.go:132
5(main.(*package_file_cache).update_cache): /home/fd0/shared/work/go/src/mod/github.com/nsf/gocode@v0.0.0-20180502111240-9d1e0378d35b/package.go:92
6(main.update_packages.func1): /home/fd0/shared/work/go/src/mod/github.com/nsf/gocode@v0.0.0-20180502111240-9d1e0378d35b/autocompletecontext.go:455
7(runtime.goexit): /home/fd0/sdk/go1.11beta2/src/runtime/asm_amd64.s:1333
```

Is there anything else I can do to get this resolved?

**Comment by fd0** [comment]
Oh, I just realized you're the one who submitted the CL that changes the export format, sorry for that ;)

Any chance you may have time to work on this before the release of Go 1.11? This will be a pain for most users.

**Comment by DisposaBoy** [comment]
Are you sure you're using the correct repo? the stacktrace shows *github.com/**nsf**/gocode*

**Comment by fd0** [comment]
Oh wow, it seems my test case was wrong, apparently I've used nsf's original version. Turns out, it works with this one. I have no idea how that happened, sorry for the noise. Closing.
