### ISSUE TITLE
Packages in /vendor not autocompleting

### ISSUE THREAD

**Issue by montanaflynn** [mdempsky/gocode#47]
After using `dep init` I don't get autocomplete results for packages inside `vendor` directory. The program still builds and runs fine and is using the code in `vendor` as I would expect. If I rename `vendor` to `vendored` then the autocomplete works fine. 

Running `go version go1.10.4 darwin/amd64`

**Comment by mdempsky** [comment]
Thank you for the report. However, I don't have experience with dep, so please bear with me. Can you clarify what you mean by "I don't get autocomplete results for packages inside `vendor` directory."?

For example, I'm imagining a layout like:

    a.go    // import "b"
    vendor/b/b.go

Are you saying that you don't get autocompletions for `b.*` while editing a.go? Or do you mean you don't get completions at all while editing vendor/b/b.go? Or something else entirely?

Perhaps a standalone example would be helpful.

**Comment by montanaflynn** [comment]
> However, I don't have experience with dep, so please bear with me.

I believe it's the same issue for other vendoring tools like `glide`, `godep`, etc... or even manually moving packages into the `./vendor` directory.

> Are you saying that you don't get autocompletions for b.* while editing a.go?

This is what I'm referring to.


Interestingly when I tried to create a small standalone example I found it works as expected for packages that only exist in `./vendor` but not for packages both in `$GOPATH/src/` and `./vendor`.

Take this example where `github.com/montanaflynn/stats` exists in both my `$GOPATH/src/` and `./vendor` while `github.com/montanaflynn/sum` only exists in `./vendor`:

```
├── main.go
└── vendor
    └── github.com
        └── montanaflynn
            ├── stats
             |      ....
            │   ├── sum.go
            │   └── variance.go
            └── sum
                └── sum.go
```

Here's what's in `main.go`
```
package main

import (
	"fmt"

	"github.com/montanaflynn/stats"
	"github.com/montanaflynn/sum"
)

func main() {
	// autocomplete works
	res1 := sum.Int([]int{1, 2, 3})
	fmt.Println(res1)

	// autocomplete does not work
	res2, err := stats.Sum(stats.Float64Data{1, 2, 3})
	fmt.Println(res2, err)
}
```

I should have also included I'm using the [atom](https://github.com/atom/atom) editor with the [go-plus](https://github.com/joefitzgerald/go-plus) package that uses go-code. There is a related issue in that repo: https://github.com/joefitzgerald/go-plus/issues/783

**Comment by trinitum** [comment]
I had a similar problem and what worked for me is `go get ./vendor/...`. After running it I've got packages in `$GOPATH/pkg/myarch/mypkg/vendor/...` and completion started working.

**Comment by myitcv** [comment]
@trinitum that should read `go install ./vendor/...`

**Comment by montanaflynn** [comment]
@trinitum @myitcv I tried those but they didn't seem to work for me

**Comment by vaijab** [comment]
> that should read go install ./vendor/...

This works. I cannot guarantee, but I think the issue started when I moved to go 1.11.

**Comment by zer09** [comment]
the ```go install ./vendor/...``` works on me, thanks @trinitum

**Comment by silenceleaf** [comment]
`go install ./vendor/...`

Is this the only way to solve this? 

I think gocode should have some "build-in" support for vendor folder dependencies. I am using glide, which will put all deps into vendor folder. Gocode will not index any file from the vendor folder.  What about provide a parameter allow me add additional package path?

**Comment by filmil** [comment]
Hi folks. I found this bug trying to find the solution to this issue.

`go install ./vendor/...` approach worked for me too.

**Comment by seagle0128** [comment]
Any update for this issue, please?

**Comment by stamblerre** [comment]
I don't think we will be working on adding improvements to handle vendor directories. If the `go install ./vendor/...` approach works for you, then I would suggest that as the fix. If anyone would like to create a PR for this, I would be happy to take a look.

**Comment by seagle0128** [comment]
I don't understand why it's closed as `wontfix`. Not only `vendor`, but also all own modules are unable to auto-complete with the new `gocode` version, while works well in the former release. Isn't it a regression bug? `go install ...` is just a workaround, and an annoying manual workaround.

**Comment by montanaflynn** [comment]
I agree with @seagle0128, and the `go install` solution didn't work for me either.

In addition to the people who thumbs up'd this issue and commented there are at least two related issues in downstream projects where people are running into this:


https://github.com/joefitzgerald/go-plus/issues/783
https://github.com/sourcegraph/go-langserver/issues/319

**Comment by stamblerre** [comment]
I'm sorry about this; I didn't realize that `go install ./vendor/...` would be an unworkable solution, as I typically use VSCode. However, I have been able to reproduce the issue, and I will try to fix it.

**Comment by stamblerre** [comment]
https://github.com/mdempsky/gocode/commit/a07fefd98fdcd9d2c16aa3f61d8e89eda396bf99 should fix this bug. Please let me know if it works for you.

**Comment by montanaflynn** [comment]
Thank you @stamblerre, it does indeed fix the issue for me!
