### ISSUE TITLE
autocomplete fails in shorthand slice syntax

### ISSUE THREAD

**Issue by mrwonko** [mdempsky/gocode#49]
``` Go
package repro

type S struct {
	Foo int
}

var _ = []S{
	/* S */ { /* autocomplete here */ },
}
```
If I comment in the S, autocomplete correctly suggests `Foo`, but not without it. This was supposedly already fixed in nsf/gocode#422, but apparently there was a regression at some point.

I'm using this in the context of VSCode on a Mac, if that makes any difference.

**Comment by mdempsky** [comment]
Thank for the report. I can reproduce this failure.

For what it's worth, there was no regression: that fix happened after mdempsky/gocode forked from nsf/gocode in 2016.

**Comment by zimmski** [comment]
This issue makes working with `gofmt -s` really hard.

**Comment by stamblerre** [comment]
I can confirm that this works correctly with `gopls`, and I would recommend using [`gopls`](https://pkg.go.dev/golang.org/x/tools/gopls) for a better Go autocompletion experience. This repository is in maintenance mode, so a fix won't be made here.
