### ISSUE TITLE
suggest: test.0011 fails with Go 1.11

### ISSUE THREAD

**Issue by mdempsky** [mdempsky/gocode#52]
Go 1.11 added a new MapRange method to reflect.Value, which causes the expectations to fail.

Unfortunately we can't just add this to the expectations because that would cause the test to fail on earlier Go releases, which we still want to maintain compatibility with. Maybe we can add support for version-specific expected outputs.

Looking at the commit where this test case was added (ddfc1800), it seems the intent was to check something related to reflect.Value's embedding of the reflect.flag type. Maybe there's another type that can test the same criteria.

**Comment by stamblerre** [comment]
Fixed temporarily with https://github.com/mdempsky/gocode/commit/32181df22c3e74ff09d4e12f1276ab3beea37659.
