### ISSUE TITLE
Reports zero candidates for syscall/js in 1.11

### ISSUE THREAD

**Issue by coreyog** [mdempsky/gocode#57]
I originally opened this bug under VSCode [here](https://github.com/Microsoft/vscode-go/issues/1874) but there trouble shooting implies it's upstream in your project. Despite setting various VSCode settings to ensure the GOOS and GOARCH were set properly. For posterity, here's that bug cut and paste here:

```
package main

import (
	"syscall/js"
)

func main() {
	js.Global().Call("alert", "Hello World")
}
```

When built with `GOOS=js GOARCH=wasm go build main.go` using Go 1.11 this produces a WASM binary without error. However VSCode shows that there's an error:

> could not import syscall/js (can't find import: "syscall/js")

I think this has to do with that namespace being experimental while wasm support stabilizes over the coming versions. I'm given very little details about the error.

As a result of the namespace not being found, intellisense also doesn't work.

I'm running VSCode 1.26.1 on Linux Mint 19 x64 with Go 1.11

I reopened the project to investigate further and when I moused over the import with it's red squiggly line, I got this error:

> build constraints exclude all Go files in /usr/local/go/src/syscall/js

I think the plugin doesn't use an altered GOOS and GOARCH when checking the code for errors.

I tried setting `go.toolsEnvVars` in the project settings but I'm still getting the could not import error on the import.

In Output I see:

> /home/corey/src/goprojects/src/wasm-hw>Finished running tool: /home/corey/src/goprojects/bin/golint
> 
> /home/corey/src/goprojects/src/wasm-hw>Finished running tool: /usr/local/go/bin/go build -i -o /tmp/go-code-check.198072839 wasm-hw
> go build runtime/internal/atomic: mkdir /usr/local/go/pkg/js_wasm: permission denied
> go build runtime/internal/sys: open /usr/local/go/pkg/js_wasm/runtime/internal/sys.a: no such file or directory
> go build internal/race: mkdir /usr/local/go/pkg/js_wasm: permission denied
> go build sync/atomic: mkdir /usr/local/go/pkg/js_wasm: permission denied
> go build internal/cpu: open /usr/local/go/pkg/js_wasm/internal/cpu.a: no such file or directory
> 
> /home/corey/src/goprojects/src/wasm-hw>Finished running tool: /usr/local/go/bin/go vet ./...

I've set my go.toolsEnvVars as follows:

```
{
  "go.toolsEnvVars": {
    "GOOS": "js",
    "GOARCH": "wasm",
    "GOROOT": "/usr/local/go",
    "GOPATH": "/home/corey/src/goprojects"
  }
}
```

GoRoot and GoPath reflect what the normal env variables are. I'm still getting the could not import error. I'm not sure why it's trying to do things in my /usr/local/go folder or how to tell it to build those files in $GOPATH/pkg.

Adding write privileges to the $GOROOT/pkg folder not only feels like a bad move, but it also doesn't entirely fix the problem. The error goes away but there's no intellisense for anything under `js`.

**Comment by dmitshur** [comment]
This looks related to #56.

**Comment by coreyog** [comment]
Ah, yes, the author of that comment appeared in my original bug over at VSCode. Their bug seems better trimmed to only the valid parts relating to gocode so I'll close mine.
