### ISSUE TITLE
external packages cannot complete

### ISSUE THREAD

**Issue by glepnir** [mdempsky/gocode#60]
### I use neovim with deoplete. my go version is 1.10.3, 
`package abc`
`import "fmt" ` 
`func Test(){`
 `fmt.Println("test gocode")}`  
### I use package abc,the gocode can't work  
`package contro`  
`import"EasyBlog/abc"`  
`func Tdd(){`  
`abc.`  
`}`
### gocode -s -debug I got these  
// Package contro provides ...
package contro
import(
	"fmt"
	"EasyBlog/abc"
)
func Tdd() {
	abc.#
}
2018/09/16 22:35:29 -------------------------------------------------------
2018/09/16 22:35:29 Error parsing input file (outer block):
2018/09/16 22:35:29  /Users/marblues/workspace/src/EasyBlog/contro/index.go:8:6: expected selector or type assertion, found ';'
2018/09/16 22:35:29 Elapsed duration: 1.014442ms
2018/09/16 22:35:29 Offset: 0
2018/09/16 22:35:29 Number of candidates found: 0
2018/09/16 22:35:29 Candidates are:
2018/09/16 22:35:29 =======================================================

**Comment by stamblerre** [comment]
Did you save the file after you added the import?

**Comment by ghost** [comment]
yeah, i meet the same problem, it seems that gocode dose not support the non standard packages' completion, can anyone fix this problem?

**Comment by stamblerre** [comment]
@chunzhouyu can you give a repro case like the one above? Make sure to save the file after you add the import. It should still work. Also make sure to run `gocode close` before `gocode -s -debug`.

**Comment by ghost** [comment]
@stamblerre sorry, i do not use emacs for golang coding right now ...

**Comment by stamblerre** [comment]
@chunzhouyu are you seeing this same issue in another editor?

**Comment by icearith** [comment]
I am exactly suffering from the same issue.

**Comment by stamblerre** [comment]
gocode should definitely work with all packages, standard library or other. If it's not, there is likely some issue with configuration. My suggestion would be to run `gocode close` to restart gocode and to make sure that you save your file after you add any imports. It's also important to rebuild gocode with the latest Go version if you recently upgraded to 1.11 or something like that.

@chunzhouyu and @icearith, if you could provide repro cases like the one @Marlboro-go provided above, that would make it easier for me to diagnose this issue. It would also be helpful to know your `$GOPATH` and `$GOROOT`, as well as any flags that you pass into gocode.

**Comment by ghost** [comment]
Maybe i will give you the repro cases if i have time @stamblerre

**Comment by glepnir** [comment]
@chunzhouyu  我解决了，但是我使用的nsf/gocode  go version 1.10.4 gocode set autobuild ture 即可，这样gocode会实时的编译.a的包在pkg下 引用的时候就会提示了

**Comment by glepnir** [comment]
@stamblerre I am sure that I saved the file. There are a lot of problems with the version of gocode after go version1.10. The standard library can't be completed. The reference package can't be completed. I communicated with the author of deoplete many times, and it is determined that it is a gocode problem. Keep trying different versions of gocode. Found that gocode autobuild option can solve this problem, it will generate a .a package under pkg to let me reference to complete

**Comment by stamblerre** [comment]
The latest version of mdempsky/gocode should work for all version of Go >= 1.10. It looks for type information by checking package files (.a files under pkg/), so that's why the autobuild setting fixed your issue. You can get type information from source, but it's significantly slower. The assumption is that you will build the project you are working on, so the .a files are expected to exist.

**Comment by glepnir** [comment]
> The latest version of mdempsky/gocode should work for all version of Go >= 1.10. It looks for type information by checking package files (.a files under pkg/), so that's why the autobuild setting fixed your issue. You can get type information from source, but it's significantly slower. The assumption is that you will build the project you are working on, so the .a files are expected to exist.

I didn't feel slow in the process of using it. It should be my gocode problem. My gocode is the version of nsf. There was no problem running on go version 1.10.4. I will rebuild the environment on the new computer with the latest mdempsky gocode to test

**Comment by ghost** [comment]
> @chunzhouyu are you seeing this same issue in another editor?

no, Maybe, just the editors that based on gocode have this issue, thanks @Marlboro-go

**Comment by glepnir** [comment]
> > @chunzhouyu are you seeing this same issue in another editor?
> 
> no, Maybe, just the editors that based on gocode have this issue, thanks @Marlboro-go

@chunzhouyu  I am sorry that I thought you were Chinese, so I spoke Chinese. I will upload the latest my neomim configuration to github later.
