### ISSUE TITLE
go-langserver + gocode integration

### ISSUE THREAD

**Issue by anjmao** [mdempsky/gocode#63]
Hi, recently I updated [go-langserver](https://github.com/sourcegraph/go-langserver) to use gocode suggest API. go-langserver is directly using internal/suggest [api](https://github.com/sourcegraph/go-langserver/blob/master/langserver/completion.go#L50) since it doesn't need to run daemon with server-client. 

Here are few problems I see.
1. Current repository contains integrations for vim, neovim, sublime etc. which are not needed for go-langserver.
2. It contains server-client daemon which is not needed for go-langserver.
3. Since I want to help improve gocode and go-langserver currently I will need to make PR in this repo and then copy-paste code to go-langserver. It's time consuming.

My suggestions:
1. Move `internal/suggest` to public `pkg/suggest`.
2. Make it go-gettable `go get github.com/mdempsky/gocode/pkg/suggest`.
3. Vendor this new package in go-langserver.

@mdempsky 
I could make PR for this change.

**Comment by alindeman** [comment]
@anjmao Sounds worthwhile of a PR to me.

**Comment by anjmao** [comment]
I'm a bit confused about gocode. 

1. Originally it was started in https://github.com/nsf/gocode
2. Later https://github.com/mdempsky/gocode forked in and added support for go 1.10 and made rewrite to be more idiomatic go.
3. Now as go 1.11 is out, module support is added to https://github.com/stamblerre/gocode and this fork is also used in vscode.
4. It looks that both @mdempsky and @stamblerre are working in Google.

As autocompletion is one of the most useful features (at least for me) would't it make sense to move gocode to some organisation so we have official place for development instead of having fork of fork of fork? Currently I even don't know to which repo should I contribute if I want to fix something.

**Comment by myitcv** [comment]
@anjmao please see https://github.com/mdempsky/gocode/issues/46#issuecomment-427282575

**Comment by stamblerre** [comment]
As @myitcv mentioned, the Go team is currently working on a language server that will replace gocode. I will maintain [mdempsky/gocode](https://github.com/mdempsky/gocode) for now, but I don't think we will be making any major changes, and we don't want to expose any APIs that others may depend on. 

I'm not sure how [go-langserver](https://github.com/sourcegraph/go-langserver) stays consistent with the internal/suggest API, but at this point, I would say that if you want to make a contribution to both repositories, you will have to make 2 PRs. I'm sorry about the state of things--it will be improved soon!

**Comment by imjustfly** [comment]
@stamblerre Very glad to hear that an official language server is in progress. When will the early beta version be released? I'm looking forward to it!

**Comment by stamblerre** [comment]
@imjustfly we don't have any specific dates set yet, but we will definitely publicize it when there is a beta version.

**Comment by saibing** [comment]
@imjustfly

https://github.com/saibing/bingo
