### ISSUE TITLE
Change in golang tools packages.Config.ParseFile breaks the build

### ISSUE THREAD

**Issue by bakito** [mdempsky/gocode#68]
in golang tools packages.Config.ParseFile was made a change, which breaks the build of this module.

https://github.com/golang/tools/commit/2f1727f1b37d7d257665debc72d4ae0b8e449748#diff-04792145c70ebd708928684da4875fe9

**Comment by stamblerre** [comment]
I assume this was referencing the breakage of https://github.com/stamblerre/gocode fork, which is resolved now.

**Comment by bakito** [comment]
Yes, sorry for raising the issue in the wrong repository. And thank you for fixing it.
