### ISSUE TITLE
gocode is slow in vim

### ISSUE THREAD

**Issue by Me1onRind** [mdempsky/gocode#69]
I find gocode is slow(about 1.7s in project) and I try to find the reason.
Then, I find the function cfg.Check() (in internal/suggest/suggest.go line 121) use about 99% time.
It's seem standard library's function and hardly  optimize it, so I wonder know if  I didn't configure correctly or It's normal phenomenon? thinks for your answer.

**Comment by stamblerre** [comment]
@Me1onRind are you using the `-source` flag? That is known to slow things down.

**Comment by Me1onRind** [comment]
Yes, I use the `-source` and `-builtin` flag.   Even only import package "fmt", gocode needs 260ms to autocomplete.
 By the way, I use vim-go order than direct use gocode, but I think It's not preblem.

**Comment by Me1onRind** [comment]
On, I find my $GOPATH/pkg is empty, is this the slow reason?

**Comment by stamblerre** [comment]
Yeah, the `-source` flag is probably causing it to be slow. Make sure to run `go build` on your project, and try running it without `-source`. That should likely fix the speed issue.

**Comment by Me1onRind** [comment]
You solved my problem perfectly! I miss understand the meaning of `-source` because my pool English power and reading code power.  Thank you very much!  ^_^

**Comment by stamblerre** [comment]
Awesome, I'm glad it's working for you now!
