### ISSUE TITLE
go get fails for Go 1.8

### ISSUE THREAD

**Issue by ramya-rao-a** [mdempsky/gocode#73]
Below is the logs from travis when trying to install gocode for Go 1.8

![image](https://user-images.githubusercontent.com/16890566/47259276-edb56280-d45b-11e8-9958-bbd8562b409b.png)

@stamblerre Did something change upstream that is causing this? There was no problem 2 days ago.

**Comment by stamblerre** [comment]
Yeah, it looks like https://github.com/golang/tools/commit/a53bc13a6341e9847bbcf8c0a0691e60e18a87c0 caused this. I think we support 2 versions behind the current Go version, so I don't think I can necessarily fix this.

I think nsf/gocode works fine for Go 1.8, though right? Maybe we can add a configuration that downloads nsf/gocode if the user's Go version is <= 1.8?

**Comment by ramya-rao-a** [comment]
Good point, I'll look into that.
