### ISSUE TITLE
Unnecessary completions provided when typing floats

### ISSUE THREAD

**Issue by ramya-rao-a** [mdempsky/gocode#74]
Trigger completions at the end of `var x = 10.`

Notice that `gocode` returns the below

![image](https://user-images.githubusercontent.com/16890566/47259532-59e59580-d45f-11e8-9b63-189281c51c7f.png)

**Comment by stamblerre** [comment]
Should be fixed as of https://github.com/mdempsky/gocode/commit/6a113bf597ab1488af38dd6afccf0474b30e64b2. Thanks for reporting this issue!
