### ISSUE TITLE
`gocode` blocks Emacs for 40-60 seconds on big projects WITHOUT `-source` enabled

### ISSUE THREAD

**Issue by rdner** [mdempsky/gocode#78]
I'm using `gocode` built from c797e02c1ebebfdad6ba94ca8814a4a52270a5fc
And `go-autocomplete-20170626.1023` for emacs installed from melpa.

The diff says that the only difference with the `emacs/go-autocomplete.el` file in this repository is:

```diff
7d6
< ;; Package-Version: 20170626.1023
55,59d53
< (defcustom ac-go-gocode-bin "gocode"
<   "Overwrite path to gocode binary"
<   :type 'string
<   :group 'go-autocomplete)
< 
104c98
<                                ac-go-gocode-bin
---
>                                "gocode"
```

Which is irrelevant to the issue I describe. 

**IMPORTANT: This emacs plugin is not using the `-source` flag**.

Recently I got very enthusiastic about the merged caching branch and decided to update my `gocode` to the latest version.

After the update my Emacs is constantly getting frozen when I work with any `.go` file. It happens once when I open a file and then sometimes when I navigate through the code. It takes around 40-60 seconds to make it work again which makes the `go-autocomplete` plugin and `gocode` completely unusable.
I know `gocode` blocks the editor because it appears on the system monitor taking the whole CPU power for this entire time. Once it's finished the editor is working again.

It has to be said my project is very big and includes Kubernetes SDK which is infamous for its size. But several points I can tell for sure:

* Once the caching branch got merged `gocode` in "standard mode" started working the same time as it would work with the `-source` flag enabled.
* Running completion does not have to be synchronous in emacs and block the whole UI.

Unfortunately, as far as I know, there is no alternative to `gocode` at the moment, so I have to deal with this, currently I'm trying to find a commit where `gocode` is still working fast as it was before.

```
go version go1.11.1 darwin/amd64
```

```
go env

GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/pragmader/Library/Caches/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/pragmader/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/opt/go/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/opt/go/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/v8/dx7bfypn52ldcfjt2913ytym0000gn/T/go-build112296599=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by stamblerre** [comment]
The cache branch tries to fall back to the source importer when it can't find export data for a file, which is my guess about why it's slow. Have you built your project? 

I will add an extra configuration setting so that the default behavior will not be to use the source importer as a fallback. In the meantime, https://github.com/mdempsky/gocode/commit/449cb34b15d3ef9fd185e6901623ff597fd330df should be the commit you can sync to.

**Comment by rdner** [comment]
>Have you built your project?

It's usually done inside a docker a container (builder), so locally I don't have any built binaries for this particular project. 

Having `-source` as an option seems to be a very good idea (I'd use it for smaller projects) but on large projects it's unfortunately not up speed yet. 

I'd appreciate if someone removed this "tries to fall back to the source importer" behavior. Because this clearly causes a regression for users, unless the source importer gets very fast and asynchronous.

**Comment by stamblerre** [comment]
Just pushed https://github.com/mdempsky/gocode/commit/6e33d3273d9c949f781985e985ca207a2276b228, which should hopefully fix the problem. Let me know if this works for you.

**Comment by cnbuff410** [comment]
@stamblerre Now sure if I should open another issue or not, but I'm also getting huge delay in the vim even though I did update to 6e33d32.

Strangely my Visual Studio Code doesn't have this issue. Perhaps a vim-go issue?

**Comment by stamblerre** [comment]
@cnbuff410: is it possible you have `let g:go_gocode_propose_source = 1` set? I'm not noticing a slowdown in Vim.

**Comment by frzifus** [comment]
@pragmader i had the same issue `go version go1.11 linux/amd64`.
it looks like https://github.com/mdempsky/gocode/commit/6e33d3273d9c949f781985e985ca207a2276b228 fixed the bug on me.

thank @stamblerre :+1:

**Comment by rdner** [comment]
Thank you very much @stamblerre for the quick fix! Seems like the issue is gone now. I appreciate your help.

**Comment by cnbuff410** [comment]
@stamblerre Nope, and I tried to set go_gocode_propose_source = 0 explicitly, still no luck.

If you don't have this issue it could be something else on my side. I will debug more.

**Comment by stamblerre** [comment]
@cnbuff410: let me know if you have any luck. I can also try to investigate. If you don't get anywhere, feel free to open a new issue.

**Comment by DisposaBoy** [comment]
... probably stating the obvious, but be sure to restart gocode after you update it e.g. by running `gocode close`

**Comment by stamblerre** [comment]
@DisposaBoy: that's a great point - I always forget to do that too. I'll add it to the issue template just as a reminder.

**Comment by cnbuff410** [comment]
Oops, that's it! Thanks for the tip @DisposaBoy .

**Comment by cnbuff410** [comment]
@stamblerre Another place to consider to put this point is probably in the README, after the `go get -u xx` instruction.
