### ISSUE TITLE
gocode.exe window keeps popping into foreground

### ISSUE THREAD

**Issue by ngomile** [mdempsky/gocode#82]
### What version of Go are you using (`go version`)?
`go1.11.1 windows/amd64`

### What editor are using?
`Sublime Text 3`

Everything is working fine it's just that every time I'm typing, the gocode window keeps on popping up. I'm under the assumption that maybe it's not even supposed to show itself since it's very distracting. I don't know what to do about it or if there's an option I have to toggle for it to stop. 

![capture](https://user-images.githubusercontent.com/39145128/47965122-90b8cf80-e04b-11e8-9e76-3be990910373.PNG)

**Comment by stamblerre** [comment]
This sounds like an issue with editor integration rather than an issue with gocode. I'd suggest raising this issue in the repository of the Sublime plugin that you are using.

**Comment by DisposaBoy** [comment]
@ngomile  This looks like a side-effect of using plain `go get gocode` on Windows. You need to use `-H=windowsgui` like https://github.com/mdempsky/gocode#setup suggests: `go get -u -ldflags -H=windowsgui github.com/mdempsky/gocode`
