### ISSUE TITLE
CPU spike caused by gocode process

### ISSUE THREAD

**Issue by FuzzOli87** [mdempsky/gocode#83]
Please answer these questions before submitting your issue. Thanks!
Also, remember that to restart gocode, you have to run `gocode close`.

### What version of Go are you using (`go version`)?
go version go1.11.2 darwin/amd64
### What editor are using?
neovim

I'm seeing really high CPU utilization upwards of 250% at times while running gocode. Completion in general seems to trigger it.

**Comment by RXminuS** [comment]
I have the same issue, it spawn dozens of Doc processes on macOS Mojave.

**Comment by FuzzOli87** [comment]
@RXminuS How were you able to inspect and find out what these processes are? Sorry for the noob question!

**Comment by dmlyons** [comment]
`top` will show gocode using a ridiculous amount of CPU.  I am experiencing this issue as well, not on Mojave yet.

**Comment by stamblerre** [comment]
I just put the caching branch of gocode behind a flag so that is no longer the default. It was causing some problems for people, so I'd suggest syncing to head and trying it out now to see if the problem still persists.

**Comment by FuzzOli87** [comment]
@stamblerre It improved some. At least the CPU spike doesn't last the entire session and only spikes when autocomplete is happening.

**Comment by stamblerre** [comment]
Ok, thanks for letting me know. Will close for now.
