### ISSUE TITLE
Go 1.X support

### ISSUE THREAD

**Issue by palsivertsen** [mdempsky/gocode#86]
From readme:
> This fork should work for all versions of Go >= 1.8

However `go get` fails on Go1.8:
```
$ docker run --rm -it golang:1.8
root@979761930cff:/go# go get -u github.com/mdempsky/gocode
# golang.org/x/tools/go/internal/gcimporter
src/golang.org/x/tools/go/internal/gcimporter/bexport.go:212: obj.IsAlias undefined (type *types.TypeName has no field or method IsAlias)
```

Go1.9 seems to work fine.

Looking at #73 seems readme should be updated to say "Go >= 1.9"

**Comment by stamblerre** [comment]
You're right, thanks for pointing that out.

**Comment by stamblerre** [comment]
Fixed by https://github.com/mdempsky/gocode/commit/fa5c674aad2c2d9b67b2339701b192d95da2849d.
