### ISSUE TITLE
Skip completions in comments

### ISSUE THREAD

**Issue by ramya-rao-a** [mdempsky/gocode#87]
It is simple enough for editors to avoid calling gocode when inside a line comment and simple strings, but it gets complicated when inside a block comment or a multi-line string.

It would be great to have gocode avoid giving completions when inside comments and strings.

**Comment by tohjustin** [comment]
Would like to take a stab at this task 😅

**Comment by ramya-rao-a** [comment]
@stamblerre Can you provide some pointers for @tohjustin ?

**Comment by tohjustin** [comment]
@ramya-rao-a @stamblerre Here's my attempt in getting `gocode` to not provide autocomplete results when the cursor is inside a comment. 

Do we want this as a default behavior for `gocode` or should I introduce this via a new flag instead?

**Comment by stamblerre** [comment]
Sorry I wasn't able to give advice, but the PR looks pretty good. I'll add some comments there. Thanks for the contribution, @tohjustin!

**Comment by tohjustin** [comment]
No worries, thanks for the quick response! 😄
