### ISSUE TITLE
support relative package paths

### ISSUE THREAD

**Issue by shaodahong** [mdempsky/gocode#89]
```bash
go version
go version go1.11.2 darwin/amd64
```

when i run `gocode -s -debug`

```bash
2018/11/23 01:23:44 gbimporter: no package found for ./db: can't find import: "/Users/xxxx/go/go_fetch-back-car/db"
2018/11/23 01:23:44 gbimporter: no package found for ./router: can't find import: "/Users/xxxx/go/go_fetch-back-car/router"
```

Q:

custom relative path package doesn't support, but the import package is true, and path `/Users/xxxx/go/go_fetch-back-car/router` is exist

In my project

main.go

```go
import (
	"fmt"

	"./db"
	"./router"
	"github.com/gin-gonic/gin"
)
```

tree

```
.
├── README.md
├── ctx
├── db
├── errorer
├── handle
├── main.go
├── router
├── test_test.go
└── utils
```
![image](https://user-images.githubusercontent.com/14831261/48916874-02ec3980-eebf-11e8-99da-93c34e4da824.png)

**Comment by frzifus** [comment]
following your tree, it looks like all the files are in one package. this means that you do not have to be import them. furthermore, I'm not sure if `"./somepkg"` would work at all.

**Comment by shaodahong** [comment]
@frzifus 

db files are new package, isn't `package main`, so need import
```go
package db

import (
	"database/sql"
	_ "github.com/go-sql-driver/mysql"
	"log"
)

var SqlDB *sql.DB
```

**Comment by shaodahong** [comment]
@frzifus oh, goland support it , but I like vscode, so I hope it can be solve

**Comment by frzifus** [comment]
Maybe this [post](https://stackoverflow.com/questions/38517593/relative-imports-in-go) will help you.

**Comment by shaodahong** [comment]
@frzifus I try it, but the result is the same, I can import it, but don't autocompletion

**Comment by MagnusHuan** [comment]
@shaodahong 我之前和你有过同样的问题，切换nsf版本的gocode 并设置gocode autobuild 解决。我的go version1.10.4 并没有尝试其他的go版本 gocode问题
![1](https://user-images.githubusercontent.com/41671631/49276233-db95fd80-f4b8-11e8-9727-737c997feb85.png)

**Comment by frzifus** [comment]
google translate tells me that... @MagnusHuan
``` I had the same problem with you before, switching the nsf version of gocode and setting gocode autobuild to solve. My go version 1.10.4 did not try other go versions gocode problem```

btw i don't see any relative path included there.

**Comment by shaodahong** [comment]
now I resolve it with `go mod`

**Comment by MagnusHuan** [comment]
> google translate tells me that... @MagnusHuan
> ` I had the same problem with you before, switching the nsf version of gocode and setting gocode autobuild to solve. My go version 1.10.4 did not try other go versions gocode problem`
> 
> btw i don't see any relative path included there.

my fault, it's relative path

**Comment by stamblerre** [comment]
Closing this issue. For a better development experience with Go modules, I would suggest using [`gopls`](https://pkg.go.dev/golang.org/x/tools/gopls).
