### ISSUE TITLE
Show const/var value in completions

### ISSUE THREAD

**Issue by segevfiner** [mdempsky/gocode#92]
It's quite useful to be able to see the value of a const/var in completions. Currently `gocode` doesn't supply this information to the editor. This is a request to add that information so that editors can show it.

The case for also doing this for variables is that consts in Go don't support any type, if you need some "constant" value that isn't scalar, e.g. a slice, you often see a global variable used instead.

Screenshot from VS Code with `godef` that does do that for consts but not for variables:
![image](https://user-images.githubusercontent.com/24731903/48982350-0adbf180-f0ea-11e8-8e63-c682334579ba.png)

### Sample Code
```go
package main

import "fmt"

const foo = "foo"
const Bar = "bar"

var baz = "baz"
var Qux = "Qux"

func main() {
	fmt.Println(foo, Bar, baz, Qux)
}
```

Originally reported at: https://github.com/Microsoft/vscode-go/issues/2146

cc @ramya-rao-a @stamblerre

**Comment by mdempsky** [comment]
Seems reasonable and doable.

Two nits that need to be clarified though:

1. Variables don't have values at compile-time, only run-time. Probably you mean you want to see their initializing statement? What should we show then for completions for `foo` given `var foo, bar = f()` (in particular if f() returns two differently typed values).

2. Constants have both a (possibly implied) expression and a value. Which should we show? Or maybe both, if the value isn't a literal?

**Comment by segevfiner** [comment]
1. Yeah I'm talking about the initialization expression. As I explained in the issue description, I often see variables used as a global constant value since `const` in Go doesn't support non-scalar values. So this makes it quite useful to be able to see such values. A large non-scalar value might need to be trimmed before showing it though...

2. Not sure. I guess the expression can be useful in some cases, and the value useful in others... For example when using `iota`, the value is useful, and the expression is, well... not so much. On the other hand, seeing something like `math.MaxUint32` is more useful than just the large number that is it's value.

**Comment by stamblerre** [comment]
This is something we've experimented with in `gopls`. Right now, we have landed on showing constant values when a user hovers on a symbol. Values are not shown for variables.

Since this repository is in maintenance mode, a fix for this won't be contributed here. If you'd like to see this behavior in `gopls`, please file an issue on the Go issue tracker.
