### ISSUE TITLE
add build on save to emacs plugin

### ISSUE THREAD

**Issue by zhangjie2012** [mdempsky/gocode#95]
go version: `go1.11 darwin/amd64`

When I save go source file, will auto rebuild complete index ? New go package model will not work well, but old package file and stand library work fine.

I try to open project in VSCode, then emacs will work fine .

So I guess emacs when save file not rebuild complete index, How to set gocode autobuild ?

**Comment by stamblerre** [comment]
I believe what's happening is that VSCode builds on save (I think the configuration is `go.buildOnSave`). This fork of gocode doesn't have the autobuild feature that [nsf/gocode](https://github.com/nsf/gocode) had. I don't have any plans to add `autobuild` or to work on the Emacs plugin. However, I would be willing to review PRs. Sorry for the inconvenience!

**Comment by stamblerre** [comment]
Closing this issue, as this repository is in maintenance mode. Any PRs are welcome. For a better Go autocompletion experience, please use [`gopls`](https://pkg.go.dev/golang.org/x/tools/gopls).
