### ISSUE TITLE
Autocomplete and dep's [ignored] tag

### ISSUE THREAD

**Issue by harikb** [mdempsky/gocode#97]
### What version of Go are you using (`go version`)?
```
> go version
go version go1.11.2 darwin/amd64
```

### What operating system and processor architecture are you using (`go env`)?

MacOSX

```
GOARCH="amd64"
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
```

### What is the debug output of `gocode`?

```
2018/12/17 14:52:04 gbimporter: no package found for git...
2018/12/17 14:52:04 gbimporter: no package found for git...
```

### What (client-side) flags are you passing into `gocode`?

`gocode -s -debug`

### What editor are using?

vscode

I have an issue where Autocomplete stopped working recently. In the logs, certain packages are listed as import-errors, but only those marked in `dep`'s `[ignored]` feature. 

### Detailed background
I use `[ignored]` in the following case when working with forks. This surprisingly complicated sequence is done to minimise changes to the fork. Typically a project includes self references (imports) and they all have to be changed to point to the fork. Then when a pull request is submit to the upline, all those unnecessary changes will have to be excluded. Here is my alternate workflow (based on suggestions from other folks), but somehow can't make `gocode` see this.

1. There is an upline repo that is `github.com/foo/bar`
2. I fork this repo to `github.com/harikb/bar`
3. If the changes I make to the repo are expected to be contributed/merged back into the main repo, I checkout `github.com/harikb/bar` under `$GOPATH/src/github.com/foo/bar`. During development, I use `[ignored]` to tell dep to just use the `github.com/foo/bar` that is available under `$GOPATH` (which is really `github.com/harikb/bar` under the hood). That is, requesting `dep` to just use what is available under `$GOPATH` and don't bother checking out a fresh copy under `<project>/vendor`.
4. Once tested, push change to github (still the fork), submit pull request, and wait for upline to merge. Since we still need a functioning system buildable during the long wait, I then use the following constraint
```
[[constraint]]
  name = "github.com/foo/bar"
  source = "https://github.com/harikb/bar.git"
  branch = "master"
```
5. Once pull request is merged, update `Gopkg.toml` with no changes required in code.

**Comment by stamblerre** [comment]
gocode does not currently work well with dep (see https://github.com/mdempsky/gocode/issues/84). My current suggestion as a work-around is to run `go install ./vendor/...` so that you have `.a` files for all your dependencies in your `$GOPATH/pkg`.

**Comment by stamblerre** [comment]
Closing this issue, as the repository is in maintenance mode, and the recommended autocompletion provider for Go modules is [`gopls`](https://pkg.go.dev/golang.org/x/tools/gopls). Any PRs to handle support for dep are welcome.
