### ISSUE TITLE
Automatic prompting function for package paths

### ISSUE THREAD

**Issue by cognidim** [mdempsky/gocode#99]
VSCODE

Now when you enter the package path in import, you can automatically prompt the path of the package containing characters. But the same is not prompted. You can only enter the full package path by yourself. How to deal with this problem?

**Comment by stamblerre** [comment]
I'm sorry, I'm not sure that I understand your question. Are you trying to autocomplete while adding imports? Are you using `goimports`?

**Comment by stamblerre** [comment]
Closing this issue as obsolete. (Maybe relevant: https://github.com/golang/go/issues/35877?)
